### ISSUE TITLE
Change in API?

### ISSUE THREAD

**Issue by wilvancleve** [MattTW/BlinkMonitorProtocol#20]
Both with curl and with blinkpy, I'm failing to successfully login to blink at the API URL:

https://rest.prod.immedia-semi.com/login

Any sense of whether this is an indication of a change to the login API?

**Comment by Vitiell0** [comment]
The API has changed, I was inspecting it last night and found this new structure.

![blink new api](https://user-images.githubusercontent.com/6282321/40917837-34cbea62-67ca-11e8-9abb-d010f3e2367a.png)

For example, to get a list of videos you can call something like `https://rest-u001.immedia-semi.com/api/v2/videos/changed?since=2018-06-01T23:11:21+0000&page=1` with your AUTH_TOKEN set in the headers.

**Comment by wilvancleve** [comment]
Thanks for the info! How are you doing the inspection?

**Comment by Vitiell0** [comment]
@wilvancleve I was able to do it using Charles: https://www.charlesproxy.com

Make sure to follow instructions for setting up SSL proxying and install the SSL cert on your phone.

**Comment by rohitsud** [comment]
Have you been able to page successfully using the `page` query parameter? It always seems to show me the first 25 videos irrespective of what I provide as its value.
